spring:
  application:
    name: kometa-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: kometa
    password: passwd
    url: jdbc:postgresql://localhost:5432/kometa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  rabbitmq:
    host: localhost

common:
  version: 0.1
  env: dev
  invite-only: true
  api:
    url: https://api.example.com/
  gateway:
    url: wss://gateway.example.com/
  limitations:
    username:
      min-length: 3
      max-length: 32
    password:
      min-length: 4
      max-length: 256
    title:
      min-length: 1
      max-length: 32
    message-content:
      min-length: 1
      max-length: 4096
    message-attachments:
      min-amount: 0
      max-amount: 10
    model-key:
      min-length: 8
      max-length: 256
    model-tokens:
      min-amount: 8
      max-amount: 2048

jwt:
  secret:

apis:
  openai:
    models:
      - gpt-4
      - gpt-4-32k
    api:
      key: 1
      url: 1
  gemini:
    models:
      - gemini-2.0-flash
      - gemini-2.5-flash-preview-04-17
    api:
      key: 1
      url: 1