spring:
  application:
    name: kometa-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: kometa
    password: passwd
    url: jdbc:postgresql://localhost:5432/kometa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  rabbitmq:
    host: localhost

api:
  version: 0.1

jwt:
  secret:

apis:
  openai:
    models:
      - gpt-4
      - gpt-4-32k
    api:
      key: 1
      url: 1
  gemini:
    models:
      - gemini-2.0-flash
      - gemini-2.5-flash-preview-04-17
    api:
      key: 1
      url: 1